using Documenter
using Printf
using Plots

include("../src/auxiliary.jl")
ENV["GKSwstype"] = "nul"

@doc raw"""
    vizme()

Generates a 2D gif from the data generated by homogeneous_dirichlet_Ez_2D.jl
The settings in the function have to by changed to match homogeneous_dirichlet_Ez.jl for a functioning script.
"""
@views function vizme()
    # numerical parameters
    nt = 1000
    nvis = 20

    #get from mulitxpu run
    dims = [2,2,1]

    #grid and plot parameters
    lx = 10
    ly = lx
    nx = 200
    ny = nx
    nx_v,ny_v = (nx-2)*dims[1],(ny-2)*dims[2]
    u  = zeros(Float32,nx_v,ny_v)
    xc      = LinRange(0, lx, nx_v)
    yc      = LinRange(0, ly, ny_v)


    anim = @animate for it = 1:nt/nvis
        load_array(@sprintf("homogeneous_dirichlet_Ez_out/out_T_%05d",it),u)
        plt = heatmap(xc, yc, u'; xlims=(xc[1], xc[end]), ylims=(yc[1], yc[end]), clims=(-1, 1), aspect_ratio=1, c=:turbo)
    end
    gif(anim, "docs/homogeneous_dirichlet_Ez.gif", fps = 10);
    return nothing
end


vizme()